### ISSUE TITLE
プログラミング教室のコンテンツ拡充

### ISSUE THREAD

**Issue by snd-07** [yutaroud/rect#117]
## デザインURL

- slackにて共有

## やったこと

1. コース一覧ページの追加
    - TOPページ
        - curriculumコンテンツでは、サマリーだけに変更
        - 応じて、教室の場所は「アクセス」コンテンツとして切り出し
    - 詳細ページの新規作成
2. よくある質問の追加
3. 教室の風景を追加
    - 実態のある教室であることを早め（FV下）で伝えて安心感を
5. ヘッダーにCTAの追加
    - LPが増えてCTAが下がるので、追従ヘッダーにボタンを入れておく
6. 講師を写真に
7. 身に付くスキルコンテンツ追加

### ソフトウェア開発・上級コース

- スライドに詳細がないので対応方法相談
    - 詳細ページを作らない場合：コース一覧に載せるかどうか
    - 詳細ページを作る場合：コンテンツをもらいたい

### 身に付くスキルコンテンツについて

- どこに入れるか
    A. TOPに入れる＠一旦Aで入れました
    B. コース詳細に入れる
    C. 別ページで作る

**Comment by yutaroud** [comment]
> 上級コース

今現時点では用意してないので、詳細ページ作らなくてOK 
コース一覧にも載せなくてOK

身につくスキルはTOPに入れるでお願いしたい！
