### ISSUE TITLE
プログラミングスクールLPのPCリサイズ

### ISSUE THREAD

**Issue by snd-07** [yutaroud/rect#131]
## 概要

- https://re-ct.co.jp/school/ をPCも含めてレスポンシブ対応する

## デザイン

- プロトタイプURL： [Figma](https://www.figma.com/proto/YcRf6ibuzm08uKX7CcVzMG/%E7%B4%8D%E5%93%81%E7%94%A8?page-id=0%3A1&node-id=125-964&node-type=frame&viewport=183%2C591%2C0.17&t=6APkSS9Eh3rSyekb-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=125%3A964)
- スクショ：slackにて添付

## 確認事項

- CTA周りの情報が増えて、若干CTAボタンが埋もれているため情報整理すると良さそうです。↓
- 変えない（今のまま）でもOKです！

|PC|SP|
|---|---|
|![Group 46](https://github.com/user-attachments/assets/4251c9dd-7b2c-4893-929d-c94e1c75a3ca)|![Frame 195](https://github.com/user-attachments/assets/d00f3e9d-f274-481a-bfcd-9b0e601ace08)|

**Comment by yutaroud** [comment]
ありがとう！
LINEとinstagramは並列でもっと目立たない感じで良いかなと思う！

**Comment by snd-07** [comment]
@yutaroud 

③のイメージでどうでしょう？もっと目立たない感じがよければ、青背景から外した方が良いかも
LPの文章、コンテンツふまえ①②も作ってみました↓

- 申し込みに関すること（一番アクションしてほしいこと）→青い背景に
- もっと教室について知るための情報→白い背景でコンテンツわける

|①|②|③|
|---|---|---|
|![スクリーンショット 2024-12-08 15 53 54](https://github.com/user-attachments/assets/79876479-c66e-4497-95b4-ff06d1aedeb2)|![スクリーンショット 2024-12-08 15 53 57](https://github.com/user-attachments/assets/c8c8c26e-5444-4887-a6e2-5e26525543cb)|![スクリーンショット 2024-12-08 15 53 56](https://github.com/user-attachments/assets/3988b97f-1356-4420-bf49-a096ab96837e)|
|文章 `その他、お問合せやご相談は お電話または公式LINEアカウントへご連絡ください` に合わせる| コメントくれた `LINEとinstagramは並列でもっと目立たない感じ`| 申し込みアクションに含めつつ、 コメントくれた `LINEとinstagramは並列でもっと目立たない感じ` （②ほどは優先度下げない）| 
|![1](https://github.com/user-attachments/assets/cf8925a5-f087-4b9d-87fd-5fdb308cfc56)|![3](https://github.com/user-attachments/assets/d934af59-9fa1-41c2-a6ea-61bb91ac3c6c)|![2](https://github.com/user-attachments/assets/87206f55-8c03-44d5-8505-bff19f7964f6)|

**Comment by yutaroud** [comment]
@snd-07 3パターンもありがとう！
それだと1がいいかな！

問い合わせと並列の方が確かに良さそう！
